ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine

RUN echo "Hi" && \
    # Cleanup
    rm -r \
    # Yarn
    /opt \
    # Npm
    /usr/local/lib/node_modules/ \
    # APK sources
    /usr/share/apk \
    # some keys
    /root/.gnupg \
    # apk cache
    /var/cache/apk \
    # some node stuff
    /usr/local/include/node/openssl/archs/darwin-i386-cc \
    /usr/local/include/node/openssl/archs/darwin64-x86_64-cc \
    /usr/local/include/node/openssl/archs/solaris-x86-gcc \
    /usr/local/include/node/openssl/archs/linux-elf \
    /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc \
    /usr/local/include/node/openssl/archs/linux-x86_64 \
    /usr/local/include/node/openssl/archs/linux-x32 \
    /usr/local/include/node/openssl/archs/BSD-x86_64 \
    /usr/local/include/node/openssl/archs/linux32-s390x \
    /usr/local/include/node/openssl/archs/linux64-s390x \
    /usr/local/include/node/openssl/archs/aix64-gcc \
    /usr/local/include/node/openssl/archs/aix-gcc \
    /usr/local/include/node/openssl/archs/linux-aarch64 \
    /usr/local/include/node/openssl/archs/linux-ppc64le \
    /usr/local/include/node/openssl/archs/linux-ppc64 \
    /usr/local/include/node/openssl/archs/linux-ppc \
    /usr/local/include/node/openssl/archs/VC-WIN64A \
    /usr/local/include/node/openssl/archs/VC-WIN32 \
    # deleted symlinks
    /usr/local/bin/npx \
    /usr/local/bin/npm \
    /usr/local/bin/yarnpkg \
    /usr/local/bin/yarn