ARG VERSION

FROM dzek69/noderasp:${VERSION}-ffmpeg

RUN echo "Hi" && \
    #
    # Install stuff
    apk add --no-cache python && \
    wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl && \
    chmod a+rx /usr/local/bin/youtube-dl